# Generated by Django 5.0.2 on 2024-02-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
