# Generated by Django 5.0.2 on 2024-02-11 19:58

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_blogmodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='upload_to',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
